Unblocking only `ezodn.com`
AdguardTeam/AdGuardSDNSFilter pull request #1419
Opened 2023-07-06 07:48 UTC by zloyden

Related to:
https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1412
https://github.com/AdguardTeam/AdGuardSDNSFilter/pull/1418#issuecomment-1623130391
Actually, excluding the domain solves the problem, but unblocking it also works on my side, and it's better because its subdomains will be blocked.

2023-07-06 07:50 UTC, AdamWr requested changes

2023-07-06 07:50 UTC, AdamWr commented on Filters/exceptions.txt
> +@@||ezodn.com^|
```suggestion
@@|ezodn.com^|
```

2023-07-06 07:59 UTC, merged

2023-07-10 07:01 UTC, AdamWr commented
As far as I can see, `ezodn.com` is already unblocked and I can close cookie notice on this page with only DNS filtering enabled.
I can reproduce it only if I add `||ezodn.com^$important` to user rules in DNS filter editor.

2023-07-10 07:20 UTC, BlazDT commented
Hmm, I enabled DNS filter only in Chrome Extension, updated it and the click did nothing.