proxima.shopimind.com
AdguardTeam/AdGuardSDNSFilter pull request #1518
Opened 2023-10-25 12:53 UTC by piquark6046

Fix https://github.com/AdguardTeam/AdguardFilters/issues/164582

2023-10-25 15:08 UTC, zloyden approved these changes

2023-10-25 18:48 UTC, Alex-302 requested changes

2023-10-25 18:48 UTC, Alex-302 commented on Filters/exceptions.txt
> +@@||proxima.shopimind.com^|
I suggest to exclude a blocking rule, and block tracking domains in our TPF.
* `||app.shopimind.com^$third-party` (https://www.imagesdepinal.com/)
* `||iss.shopimind.com^$third-party` (https://www.drone-fpv-racer.com/)

2023-10-26 17:20 UTC, Alex-302 approved these changes

2023-10-26 17:20 UTC, merged