fix #71289 mobile.yahoo.com
AdguardTeam/AdGuardSDNSFilter pull request #546
Opened 2021-01-14 13:26 UTC by Sergey-Lyapin

https://github.com/AdguardTeam/AdguardFilters/issues/71289

2021-01-14 13:39 UTC, ameshkov requested changes
Let's only unblock one subdomain, i.e. unblock clicks.

I don't like the idea of unblocking the whole tracking service

2021-01-15 11:42 UTC, zloyden approved these changes

2021-01-15 13:12 UTC, Sergey-Lyapin commented
@Alex-302

2021-01-18 21:05 UTC, Alex-302 approved these changes

2021-01-19 07:15 UTC, ameshkov approved these changes

2021-01-19 07:20 UTC, merged